### ISSUE TITLE
Not working on Windows 7

### ISSUE THREAD

**Issue by akaic** [Sauermann/psopt-installer#4]
First of all, thank you for this great project.

I got several problems during the installations.
Following the instructions, first I noticed there were many errors saying that g++ and gfortran are not found. Though I was not at all sure if this was fine, I solved this problem by mingw-get.

Next, it started to make a beeping popup saying zlib1.dll is missing. Again, using mingw-get (following http://stackoverflow.com/questions/25542055/mingw-c-compiler-zlib1-dll-missing-error) "solved" this problem.

But still, the installation makes many errors and obstacle does not work because there's no cs.h. Since the errors occurring in the installation are so many, I can't describe specific ones. I'm actually logging everything right now (because I can't understand what's happening).

I will put the log once the installation is "done" again, but at least I can tell that the first error is:

...
OpenBLAS-0.2.13/utest/test_rotmg.c
OpenBLAS-0.2.13/utest/test_swap.c
OpenBLAS-0.2.13/version.h
ln: creating symbolic link `libopenblas.a' to `libopenblas_sandybridgep-r0.2.13.a': No such file or directory
make: [libs] Error 1 (ignored)
...

Your help is very much appreciated.

**Comment by Sauermann** [comment]
First thing, I notice is that you said that you solved installing g++ and gfortran using mingw-get.
However for this psopt installation g++ and gfortran have to be installed with TDM-GCC and not MinGW. (I never tested it with MinGW-only, because 64-bit is the intended platform)
That is most likely the reason for the zlib and following problems.

May I ask you to test it with TDM-GCC and report back, if that solves your problem. It would probably be best if you uninstall the mingw-versions of g++ and gfortran, since they might interfere.

**Comment by akaic** [comment]
Ah, it was just a silly mistake: I put MinGW path to fstab. I'm so sorry.

And it worked!!

Again, thank you very much for this great installer!! I was struggling for days to install PSOPT!!

**Comment by Sauermann** [comment]
Glad to hear that it worked!
